# Generated by Django 5.2.10 on 2026-01-29 12:05

import django.db.models.deletion
import mdeditor.fields
import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_zh", models.CharField(max_length=50, verbose_name="分类名(中文)")),
                (
                    "name_en",
                    models.CharField(blank=True, max_length=50, verbose_name="分类名(英文)"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
            ],
            options={
                "verbose_name": "文档分类",
                "verbose_name_plural": "文档分类",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="将不同语言版本的同一篇文章设为相同的ID",
                        verbose_name="多语言关联ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("zh", "中文"), ("en", "English")],
                        default="zh",
                        max_length=2,
                        verbose_name="语言",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("content", mdeditor.fields.MDTextField(verbose_name="文档内容")),
                ("views", models.PositiveIntegerField(default=0, verbose_name="浏览量")),
                ("is_public", models.BooleanField(default=True, verbose_name="是否公开")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knowledge.category",
                        verbose_name="所属分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识文档",
                "verbose_name_plural": "知识文档",
                "ordering": ["-created_at"],
            },
        ),
    ]
