# Generated by Django 5.2.10 on 2026-01-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="language",
            field=models.CharField(
                choices=[("zh", "中文"), ("zh-hant", "繁體中文"), ("en", "English")],
                default="zh-hant",
                max_length=10,
                verbose_name="语言",
            ),
        ),
    ]
