# Generated by Django 5.2.10 on 2026-01-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100, verbose_name="公司名称")),
                ("contact_person", models.CharField(max_length=50, verbose_name="联系人")),
                ("contact_info", models.CharField(max_length=100, verbose_name="联系方式")),
                ("content", models.TextField(verbose_name="需求/留言内容")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "is_handled",
                    models.BooleanField(default=False, verbose_name="是否已处理"),
                ),
            ],
            options={
                "verbose_name": "客户留言",
                "verbose_name_plural": "客户留言",
            },
        ),
    ]
